version: '3'

services:
  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'cuongtest'
       MYSQL_USER: 'admin'
       MYSQL_PASSWORD: 'cuongtest123'
       MYSQL_ROOT_PASSWORD: 'cuongtest123'
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/userlookup/
    ports:
      - "8000:8000"
    depends_on:
      - db
